# ===============================
# DATA SOURCE
# ===============================
# Set here configurations for the database connection
# ===============================
# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automatically created afresh for every start of application
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: 'postgres'
    password: '2468'
    driver-class-name: org.postgresql.Driver
    data: classpath:database/populate.sql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create #none для того, чтобы добавить схему в datasource: schema:classpath:database/filename.sql
    naming:
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate.show-sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
server:
  port: 8080