INSERT INTO ALBUM (id, genre, artist, title, description, src) VALUES (1, 'Nu metal', 'Deftones', 'Adrenaline', 'Выпущен: 1 октября 1995 года Лейбл: Maverick, Warner Bros Формат: CD, кассета, LP, цифровая дистрибуция', 'adrenaline.jpg');
INSERT INTO ALBUM (id, genre, artist, title, description, src) VALUES (2, 'Nu metal', 'Deftones', 'Around The Fur', 'Выпущен: 24 октября 1997 года Лейбл: Maverick, Warner Bros Формат: CD, кассета, LP, цифровая дистрибуция', 'around_the_fur.jpg');
INSERT INTO ALBUM (id, genre, artist, title, description, src) VALUES (3, 'Nu metal', 'Deftones', 'White Pony', 'Выпущен: 20 июня 2000 года Лейбл: Maverick Формат: CD, кассета, LP, цифровая дистрибуция', 'white_pony.jpg');
INSERT INTO ALBUM (id, genre, artist, title, description, src) VALUES (4, 'Nu metal', 'Deftones', 'Deftones', 'Выпущен: 20 мая 2003 года Лейбл: Maverick Формат: CD, LP, цифровая дистрибуция', 'deftones.jpg');
INSERT INTO ALBUM (id, genre, artist, title, description, src) VALUES (5, 'Nu metal', 'Deftones', 'Saturday Night Wrist', 'Выпущен: 31 октября 2006 года Лейбл: Maverick Формат: CD, LP, цифровая дистрибуция', 'saturday_night_wrist.jpg');
INSERT INTO ALBUM (id, genre, artist, title, description, src) VALUES (6, 'Nu metal', 'Deftones', 'Diamond Eyes', 'Выпущен: 4 мая 2010 года Лейбл: Reprise, Warner Bros Формат: CD, LP, цифровая дистрибуция', 'diamond_eyes.jpg');
INSERT INTO ALBUM (id, genre, artist, title, description, src) VALUES (7, 'Nu metal', 'Deftones', 'Koi No Yokan', 'Выпущен: 13 ноября 2012 года Лейбл: Reprise, Warner Bros Формат: CD, LP, цифровая дистрибуция', 'koi_no_yokan.jpg');
INSERT INTO ALBUM (id, genre, artist, title, description, src) VALUES (8, 'Nu metal', 'Deftones', 'Gore', 'Выпущен: 8 апреля 2016 года + Лейбл: Reprise, Warner Bros Формат: CD, LP, цифровая дистрибуция', 'gore.jpg');
--
INSERT INTO TRACK (id, title, artist, description, src, album_id) VALUES (1, 'Bored', 'Deftones', 'some desctiption', '01-Bored.mp3', 1);
INSERT INTO TRACK (id, title, artist, description, src, album_id) VALUES (2, 'MinusBlindfold', 'Deftones', 'some desctiption', '02-Minus_Blindfold.mp3', 1);
INSERT INTO TRACK (id, title, artist, description, src, album_id) VALUES (3, 'One_Weak', 'Deftones', 'some desctiption', '03-One_Weak.mp3', 1);
INSERT INTO TRACK (id, title, artist, description, src, album_id) VALUES (4, 'Nosebleed', 'Deftones', 'some desctiption', '04-Nosebleed.mp3', 1);
INSERT INTO TRACK (id, title, artist, description, src, album_id) VALUES (5, 'Lifter', 'Deftones', 'some desctiption', '05-Lifter.mp3', 1);
INSERT INTO TRACK (id, title, artist, description, src, album_id) VALUES (6, 'Root', 'Deftones', 'some desctiption', '06-Root.mp3', 1);
INSERT INTO TRACK (id, title, artist, description, src, album_id) VALUES (7, '7_Words', 'Deftones', 'some desctiption', '07-7_Words.mp3', 1);
INSERT INTO TRACK (id, title, artist, description, src, album_id) VALUES (8, 'Birthmark', 'Deftones', 'some desctiption', '08-Birthmark.mp3', 1);
INSERT INTO TRACK (id, title, artist, description, src, album_id) VALUES (9, 'Engine_No_9', 'Deftones', 'some desctiption', '09-Engine_No_9.mp3', 1);
INSERT INTO TRACK (id, title, artist, description, src, album_id) VALUES (10, 'Fireal', 'Deftones', 'some desctiption', '10-Fireal.mp3', 1);
INSERT INTO TRACK (id, title, artist, description, src, album_id) VALUES (11, 'Fist', 'Deftones', 'some desctiption', '11-Fist.mp3', 1);